### ISSUE TITLE
form validation doesn't coerce to string

### ISSUE THREAD

**Issue by andreaseger** [dry-rb/dry-validation#113]
According to [this](http://dry-rb.org/gems/dry-validation/forms/) the form validation does coercion before validating.
This seems to be not working if I want to ensure something is a string.

```
require 'bundler/inline'
gemfile true do
  gem 'dry-validation'
end

schema = Dry::Validation.Form do
  key(:user_id).required(:str?)
  key(:age).required(:int?)
end

p schema.call('user_id' => 123, 'age' => '55')
#<Dry::Validation::Result output={:user_id=>123, :age=>55} messages={:user_id=>["must be a string"]}>
```

So the `age` got coerced to an integer but `user_id` wasn't coerced to a string. This seems inconsistent and confusion. Right now it seems like I can't be sure when coercion is done and when not.

**Comment by timriley** [comment]
Hi there! You're right to expect form schemes to coerce the input data. However, it's set up only to do this when the input data are all strings, since this is the shape that form posts take in real usage. In a normal rack-processed form post, you'd never get a Ruby integer back, you'd always have it in string form.

This is why the form schema works as it does, and since it suits to use case (form posts), I don't expect it'd change to handle coercion a from arbitrary non-strong input data.

**Comment by andreaseger** [comment]
ok so `required(:str?)` is handled in a special way where as all other type checks try to perform coercion. We know that in real scenarios you have strings anyway so coercion to it is pointless. We just noticed this behavior during tests and where a bit surprised.

**Comment by solnic** [comment]
@andreaseger `:str?` in `Form` schemas is not handled at all, it's just being ignored since the assumption is that values are strings already.
