### ISSUE TITLE
Form: eql? predicate fails with maybe macro

### ISSUE THREAD

**Issue by jodosha** [dry-rb/dry-validation#128]
```ruby
require 'bundler/setup'
require 'dry-validation'

form = Dry::Validation.Form do
  required(:foo).maybe(eql?: '23')
end

result = form.call('foo' => '')
puts result.success?
puts result.messages[:foo].inspect

__END__

Expected:
  false
  ['must be equal to 23']

Actual:
  true
  nil
```

```
GIT
  remote: git://github.com/dry-rb/dry-logic.git
  revision: e649fad58546e8e53a048d310c554ad910466a93

GIT
  remote: git://github.com/dry-rb/dry-types.git
  revision: 394fa8b62966fd398f84b83cc712e5b1355f4af7

GIT
  remote: git://github.com/dry-rb/dry-validation.git
  revision: 59fb0a09c4997db95076b49082dc68445ead4630
```

**Comment by jodosha** [comment]
Similar failure with:

```ruby
required(:foo).maybe(eql?: '23')
result = form.call('foo' => '')
```

**Comment by timriley** [comment]
This look like the `maybe` macro working as expected. Since in this case it will expand to `none? | eql?('23')`, passing it an empty string as input will be valid.

If you want a value to equal '23', then a `required(eql?: '23')` rule seems to make more sense to me here.

Does that make sense to you? If so, feel free to close this issue, or otherwise let me know if I'm misunderstanding your test here :)

**Comment by jodosha** [comment]
@timriley Yes, thanks again for your reply!

As side note, it takes time to grasp how `maybe` expands. This is something that we should take care of. 😄
