### ISSUE TITLE
Evaluate custom predicates in the context of the validator

### ISSUE THREAD

**Issue by AMHOL** [dry-rb/dry-validation#148]
This way we could create a set of custom predicates that make use of injected variables, such as:

```ruby
require 'dry-validation'

User = Struct.new(:name, :email)

class UserRepository
  USERS = []

  def create(attributes)
    USERS << User.new(*attributes.values_at(:name, :email))
  end

  def find_by_email
    USERS.find { |email| user.email == email }
  end
end

module CustomPredicates
  include Dry::Logic::Predicates

  predicate(:unique?) do |value|
    uniqueness_finder.call(value).nil?
  end
end

UserSchema = Dry::Validation.JSON do
  configure do
    option :uniqueness_finder

    config.predicates = CustomPredicates

    def self.messages
      super.merge(en: { errors: { unique?: 'must be unique' } })
    end
  end

  required(:name).required
  required(:email).required(:unique?)
end

user_repo = UserRepository.new
user_validator = UserSchema.with(uniqueness_finder: user_repo.method(:find_by_email))
user_repo.create(name: 'John', email: 'john@dry-rb.org')

user_validator.call(
  name: 'John',
  email: 'john@dry-rb.org'
)
# Failure
user_validator.call(
  name: 'Jill',
  email: 'jill@dry-rb.org'
)
# Success
```

/cc @solnic, @timriley @jodosha

**Comment by jodosha** [comment]
@AMHOL This could be a great feature.

I'm thinking about CSRF protection too. When the `:_csrf_token` is sent within the body of a request, a framework needs to verify the input value matches with the one stored in the session.

As now, it would be an extra step after the validations. But with this feature, CSRF check can be integrated within data validations, which makes sense.

👍

**Comment by solnic** [comment]
You can achieve that w/o the complexity that comes with changing exec context of predicates. Predicate interface is very simple, you can provide your own objects as predicates and register them under predicate registry that you can share across schemas. We can easily marry that with dry-container API so that custom predicate objects can be provided through IoC.

Defo 👎 for executing predicates in the context of schema. External predicates should have their own exec context. Besides, you can always delegate predicate application to an external predicate and pass in a dependency as a predicate argument.

**Comment by musaffa** [comment]
Has anyone come up with a solution to this problem?
