### ISSUE TITLE
maybe(:array?) seems to neutralize every nested rule 

### ISSUE THREAD

**Issue by ptolts** [dry-rb/dry-validation#288]
```
schema = Dry::Validation.Form do
  optional(:line_items).maybe(:array?).each do
    schema do
      optional(:variant_id).maybe(:int?)
      optional(:quantity).maybe(:int?)
    end
  end
end

puts schema.call(line_items: [{ variant_id: 1, quantity: 'invalid_quantity' }]).inspect

#<Dry::Validation::Result output={:line_items=>[{:variant_id=>1, :quantity=>"invalid_quantity"}]} errors={}>
```

Seems to function as I intended when I remove the `maybe(:array?)`, but it should probably work both ways, or blow up.

**Comment by solnic** [comment]
you want this:

```
schema = Dry::Validation.Form do
  optional(:line_items).maybe do
    each do
      schema do
        optional(:variant_id).maybe(:int?)
        optional(:quantity).maybe(:int?)
      end
    end
  end
end
```

This is because chaining is not supported, also `each` automatically adds `array?` check for you, although that's too implicit, so I'll be changing that before 1.0.0. Chaining might be supported later, not sure yet, if it turns out to be too hard I'll just make it raise an error when somebody tries to chain.

**Comment by ptolts** [comment]
Thanks 👍
