### ISSUE TITLE
Add record-level errors key to correspond with ActiveRecord functionality

### ISSUE THREAD

**Issue by kevinrood** [dry-rb/dry-validation#310]
First off, thank you for this awesome gem and for the work you are doing to maintain it!

ActiveRecord uses a convention of assigning record-level error messages to a special key, `:base`. Please see [this reference](http://guides.rubyonrails.org/active_record_validations.html#validates-with) for more information.

It would be great if `dry-validation` provided this facility for [custom validation blocks](http://dry-rb.org/gems/dry-validation/custom-validation-blocks/). Currently, custom validation blocks assign the related error message to the last key in an array of keys. In this example:

```ruby
validate(error_message_key?: [:field_one, :field_two, :field_three]) do |field_one, field_two, field_three|
  # perform validation here
end
```

If validation fails, the error message associated with `:error_message_key?` will be assigned to `:field_three`. This type of validation works well for record-level validation and it would be ideal to control which key is used for this error message in the errors collection (or, at least override the default field name) so that record-level validation failures can be displayed to the user in a special manner.

I found a work around that fits my situation, but it would be nice if this feature were available in `dry-validation`.

**Comment by georgemillo** [comment]
I second the request for this feature; I was going to post something similar. I hit a brick wall while trying to port some of my ActiveModel validations to dry-v because I couldn't get the error message to appear on a key that made sense. 

Perhaps the best solution would be the most flexible one: make it possible to specify the *key within the `.errors` hash*  that a particular rule will assign error messages too. (This is actually how ActiveModel does it if I remember correctly - doesn't `errors.add` AM let you add an error to *any* arbitrary key, not necessarily `base` or a name that corresponds to one of the model's attributes?

**Comment by solnic** [comment]
This will be possible in 1.0.0

**Comment by mottalrd** [comment]
@solnic  thank you for working on that. Do you have any update? Any way we can help?

**Comment by solnic** [comment]
@mottalrd we started working on [dry-schema](https://github.com/dry-rb/dry-schema/pull/3) first, once this is done we'll move to updating dry-validation to use it.

**Comment by flash-gordon** [comment]
The first release of dry-schema is out and we're working on dry-validation. During this work, we're cleaning up the backlog. As Piotr mentioned, this feature will be supported in the 1.0.0 release, you can track progress in https://github.com/dry-rb/dry-validation/pull/440
