### ISSUE TITLE
No guide for migrating from < v1.0.x to v1.0.x

### ISSUE THREAD

**Issue by baburdick** [dry-rb/dry-validation#539]
I've looked through the [README](https://github.com/dry-rb/dry-validation/blob/master/README.md), the [CHANGELOG](https://github.com/dry-rb/dry-validation/blob/master/CHANGELOG.md) and the [user guide](https://dry-rb.org/gems/dry-validation/). And I'm not seeing a guide for how to migrate from an existing set of validations based on the most recent version of dry-validation prior to the new v1.0.x to a working set against the new v1.0.x.

Where do your loyal users most easily find their way into the new world?

In particular, when using with the config gem (ala https://github.com/railsconfig/config#validation), I'm seeing:
```
NoMethodError: undefined method `Schema' for Dry::Validation:Module
```

**Comment by waiting-for-dev** [comment]
[dry-validation v1.0.x announcement on dry-rb news blog](https://dry-rb.org/news/2019/06/10/dry-validation-1-0-0-released/#upgrading-from-dry-validation-0-x) refers to [Igor Morozov's post](https://www.morozov.is/2019/05/31/upgrading-dry-gems.html) as a migration guide. Additionally, it recommends checking out Readmes for dry-validation, dry-types and dry-schema.

Besides, [@solnic talked on twitter](https://twitter.com/_solnic_/status/1136938552422477824) about writing an upgrade guide. But I guess this idea has been abandoned in favor of Igor Morozov's post (it makes sense, why repeat a great work when it has already been done).

If you still are in troubles, as it is also said in the announcement:

> If you need help with upgrading, please do not hesitate to ask questions either on our discussion forum or community chat.

**Comment by solnic** [comment]
I started writing an upgrade guide and realized two things:

1) I was mostly rephrasing Igor's guide
2) It's practically speaking impossible to cover all the cases
3) It's gonna be simpler to answer any potential support questions
4) I was too tired to do anything

> In particular, when using with the config gem (ala https://github.com/railsconfig/config#validation)

Actually, I forked `config` gem and updated it to use `dry-schema` instead, see https://github.com/solnic/config/tree/switch-to-dry-schema - I opened a WIP PR too [here](https://github.com/railsconfig/config/pull/220) but couldn't finish it because their spec suite is broken, I couldn't run it locally, it fails on travis too.

I'm closing this because there's no upgrade guide and I'm not gonna write it. I'm more than happy to accept a contribution in the form of such guide though. We typically use GH's wiki for that.

ps. for support questions please use our forum and/or chat, issue templates mention this.
