### ISSUE TITLE
`Dry::Validation::Result` lacks an `#output` method similar to `Dry::Schema::Result`

### ISSUE THREAD

**Issue by postmodern** [dry-rb/dry-validation#728]
## Describe the bug

[Dry::Schema::Result](https://rubydoc.info/gems/dry-schema/Dry/Schema/Result#output-instance_method) aliases `#to_h` to `#output`, where as [Dry::Validation::Result](https://rubydoc.info/gems/dry-validation/Dry/Validation/Result#to_h-instance_method) only defines a `#to_h` method. I feel like `Dry::Validation::Result` should be symmetrical to `Dry::Schema::Result` to allow for interchangeability.

**Comment by solnic** [comment]
This is a private method, `#to_h` should be used in places where you want to get back processed/validated hash.

**Comment by postmodern** [comment]
@solnic do you mean `Dry::Validation::Result#output` is private or `Dry::Schema::Result#output` *should* be private? If `Dry::Validation::Result#output`  than maybe `Dry::Schema::Result#output` should also be private for consistency?

**Comment by solnic** [comment]
@postmodern oof I see where the confusion comes from - the `param` definition is [marked as private](https://github.com/dry-rb/dry-schema/blob/main/lib/dry/schema/result.rb#L29) but that doesn't have any effect since YARD doesn't know about our `param` DSL and then there's the actual method which is missing `@api private` 🤦. I'll fix that.
